### ISSUE TITLE
Extra space in github visualization of notebook files

### ISSUE THREAD

**Issue by ulya-tkch** [cleanlab/examples#30] opened 2022-12-05 18:05 UTC
There is a lot of extra space (not seen during initial commit) in each cell of each of the notebook files. Is this intentional?
<img width="1187" alt="Screen Shot 2022-12-05 at 11 03 40 AM" src="https://user-images.githubusercontent.com/10901697/205709755-f5bcbc15-1819-454b-97f9-5b202c0cf283.png">

**Comment by huiwengoh** [comment] 2022-12-05 18:12
The extra lines are not shown in the git diff, nor do you see them if the notebook is cloned locally, unsure why they are showing in the github viewer. Need to investigate this more.

**Comment by huiwengoh** [comment] 2022-12-05 20:53
This appears to be a GitHub-wide issue and not caused by our code. Closing issue as it does not require a fix from us.

**Closed as completed by huiwengoh** 2022-12-05 20:53 UTC
